const mongoose = require('mongoose');
require('dotenv').config();
const Recipe = require('./src/models/Recipe');

const recipes = [
  {
    title: 'Pasta Carbonara',
    description: 'Classic Italian pasta with creamy sauce made with eggs, cheese, and pancetta. A traditional Roman dish that is simple yet delicious.',
    ingredients: 'Spaghetti, eggs, pecorino cheese, guanciale, salt, black pepper, parmesan',
    preparationTime: 20,
    servings: 4,
    difficulty: 'medium',
    category: 'principal',
    isVegan: false,
    isGlutenFree: false,
    rating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop',
  },
  {
    title: 'Margherita Pizza',
    description: 'Fresh and simple pizza with tomato sauce, mozzarella, basil, and olive oil. A classic Italian pizza.',
    ingredients: 'Pizza dough, tomato sauce, mozzarella, fresh basil, olive oil, salt',
    preparationTime: 30,
    servings: 2,
    difficulty: 'easy',
    category: 'principal',
    isVegan: false,
    isGlutenFree: false,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=400&h=400&fit=crop',
  },
  {
    title: 'Caesar Salad',
    description: 'Crispy romaine lettuce with creamy Caesar dressing, croutons, and parmesan cheese.',
    ingredients: 'Romaine lettuce, Caesar dressing, croutons, parmesan cheese, anchovies, lemon',
    preparationTime: 15,
    servings: 2,
    difficulty: 'easy',
    category: 'entrante',
    isVegan: false,
    isGlutenFree: true,
    rating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=400&fit=crop',
  },
  {
    title: 'Chocolate Lava Cake',
    description: 'Decadent chocolate cake with a molten center. Perfect for chocolate lovers. Best served warm with vanilla ice cream.',
    ingredients: 'Dark chocolate, butter, eggs, sugar, flour, vanilla extract',
    preparationTime: 25,
    servings: 2,
    difficulty: 'medium',
    category: 'postre',
    isVegan: false,
    isGlutenFree: false,
    rating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop',
  },
  {
    title: 'Vegan Buddha Bowl',
    description: 'Colorful and nutritious bowl with quinoa, roasted vegetables, chickpeas, and tahini dressing. Perfect for a healthy meal.',
    ingredients: 'Quinoa, chickpeas, sweet potato, spinach, carrots, tahini, lemon juice, olive oil',
    preparationTime: 30,
    servings: 1,
    difficulty: 'easy',
    category: 'principal',
    isVegan: true,
    isGlutenFree: true,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=400&fit=crop',
  },
  {
    title: 'Tiramisu',
    description: 'Italian dessert made with layers of ladyfingers dipped in coffee and mascarpone cream. A classic no-bake dessert.',
    ingredients: 'Ladyfingers, coffee, mascarpone cheese, eggs, sugar, cocoa powder',
    preparationTime: 40,
    servings: 6,
    difficulty: 'medium',
    category: 'postre',
    isVegan: false,
    isGlutenFree: false,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=400&h=400&fit=crop',
  },
  {
    title: 'Grilled Salmon',
    description: 'Fresh salmon fillet grilled to perfection with lemon and herbs. A protein-rich and healthy main course.',
    ingredients: 'Salmon fillet, lemon, olive oil, dill, garlic, salt, pepper',
    preparationTime: 20,
    servings: 2,
    difficulty: 'easy',
    category: 'principal',
    isVegan: false,
    isGlutenFree: true,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=400&fit=crop',
  },
  {
    title: 'Garlic Bread',
    description: 'Crispy bread with garlic butter and parsley. Perfect as an appetizer or side dish.',
    ingredients: 'Baguette, butter, garlic, parsley, salt, oregano',
    preparationTime: 10,
    servings: 4,
    difficulty: 'easy',
    category: 'entrante',
    isVegan: false,
    isGlutenFree: false,
    rating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd5e1e5?w=400&h=400&fit=crop',
  },
  {
    title: 'Smoothie Bowl',
    description: 'Thick smoothie base topped with granola, fresh berries, and coconut. Great for breakfast or a snack.',
    ingredients: 'Frozen berries, banana, yogurt, honey, granola, coconut flakes, berries',
    preparationTime: 10,
    servings: 1,
    difficulty: 'easy',
    category: 'refrigerio',
    isVegan: false,
    isGlutenFree: true,
    rating: 4.3,
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=400&fit=crop',
  },
  {
    title: 'Thai Green Curry',
    description: 'Aromatic and spicy Thai curry with coconut milk, green chilies, and chicken. Served with rice.',
    ingredients: 'Chicken, green curry paste, coconut milk, Thai basil, green chilies, lime leaves, rice',
    preparationTime: 35,
    servings: 4,
    difficulty: 'medium',
    category: 'principal',
    isVegan: false,
    isGlutenFree: true,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e4e6a?w=400&h=400&fit=crop',
  },
  {
    title: 'Caprese Sandwich',
    description: 'Fresh sandwich with mozzarella, tomato, basil, and balsamic vinegar on crusty bread.',
    ingredients: 'Bread, mozzarella, tomato, fresh basil, balsamic vinegar, olive oil, salt, pepper',
    preparationTime: 10,
    servings: 2,
    difficulty: 'easy',
    category: 'entrante',
    isVegan: false,
    isGlutenFree: false,
    rating: 4.2,
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=400&fit=crop',
  },
  {
    title: 'Avocado Toast',
    description: 'Creamy mashed avocado on toasted bread with lime, chili, and olive oil. A trendy and healthy breakfast.',
    ingredients: 'Bread, avocado, lime, chili flakes, olive oil, salt, pepper, tomato',
    preparationTime: 8,
    servings: 1,
    difficulty: 'easy',
    category: 'refrigerio',
    isVegan: true,
    isGlutenFree: false,
    rating: 4.4,
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=400&fit=crop',
  },
  {
    title: 'Beef Tacos',
    description: 'Mexican-style tacos with seasoned ground beef, fresh toppings, and salsa. Fun and quick meal.',
    ingredients: 'Ground beef, taco shells, lettuce, tomato, cheese, salsa, sour cream, cilantro',
    preparationTime: 20,
    servings: 4,
    difficulty: 'easy',
    category: 'principal',
    isVegan: false,
    isGlutenFree: false,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=400&fit=crop',
  },
  {
    title: 'Mango Lassi',
    description: 'Refreshing Indian yogurt-based drink with mango pulp. Perfect for hot days.',
    ingredients: 'Mango puree, yogurt, milk, honey, cardamom, ice',
    preparationTime: 5,
    servings: 2,
    difficulty: 'easy',
    category: 'bebida',
    isVegan: false,
    isGlutenFree: true,
    rating: 4.3,
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=400&h=400&fit=crop',
  },
  {
    title: 'Quinoa Stuffed Peppers',
    description: 'Colorful bell peppers filled with quinoa, vegetables, and herbs. A vegan main course.',
    ingredients: 'Bell peppers, quinoa, black beans, corn, onion, garlic, cumin, olive oil',
    preparationTime: 40,
    servings: 4,
    difficulty: 'medium',
    category: 'principal',
    isVegan: true,
    isGlutenFree: true,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=400&fit=crop',
  },
  {
    title: 'Cheesecake',
    description: 'Creamy and rich cheesecake with graham cracker crust. A decadent dessert.',
    ingredients: 'Cream cheese, sugar, eggs, graham crackers, butter, vanilla extract',
    preparationTime: 60,
    servings: 8,
    difficulty: 'medium',
    category: 'postre',
    isVegan: false,
    isGlutenFree: false,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-742a28e27c5d?w=400&h=400&fit=crop',
  },
  {
    title: 'Vegetable Stir Fry',
    description: 'Quick and healthy stir-fried vegetables with soy sauce and ginger. Served over rice.',
    ingredients: 'Broccoli, carrots, bell peppers, snap peas, ginger, garlic, soy sauce, sesame oil, rice',
    preparationTime: 20,
    servings: 2,
    difficulty: 'easy',
    category: 'principal',
    isVegan: true,
    isGlutenFree: true,
    rating: 4.2,
    imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b8?w=400&h=400&fit=crop',
  },
  {
    title: 'Iced Coffee',
    description: 'Cold and refreshing coffee drink with ice and milk. Perfect for coffee lovers.',
    ingredients: 'Coffee, ice, milk, sugar, vanilla extract',
    preparationTime: 5,
    servings: 1,
    difficulty: 'easy',
    category: 'bebida',
    isVegan: false,
    isGlutenFree: true,
    rating: 4.1,
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?w=400&h=400&fit=crop',
  },
  {
    title: 'Falafel',
    description: 'Crispy fried chickpea balls with spices. A popular Middle Eastern appetizer or snack.',
    ingredients: 'Chickpeas, onion, garlic, cilantro, parsley, cumin, coriander, flour, baking powder, oil',
    preparationTime: 25,
    servings: 4,
    difficulty: 'medium',
    category: 'entrante',
    isVegan: true,
    isGlutenFree: false,
    rating: 4.4,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=400&fit=crop',
  },
  {
    title: 'Lemon Bars',
    description: 'Tangy and sweet lemon bars with buttery shortbread crust. A classic dessert.',
    ingredients: 'Flour, butter, sugar, eggs, lemon juice, lemon zest, powdered sugar',
    preparationTime: 35,
    servings: 12,
    difficulty: 'easy',
    category: 'postre',
    isVegan: false,
    isGlutenFree: false,
    rating: 4.3,
    imageUrl: 'https://images.unsplash.com/photo-1565958011457-41d86d8b5b13?w=400&h=400&fit=crop',
  },
  {
    title: 'Spaghetti Aglio e Olio',
    description: 'Simple Italian pasta with garlic, olive oil, and red pepper flakes. A classic minimalist dish.',
    ingredients: 'Spaghetti, garlic, olive oil, red pepper flakes, parsley, salt, lemon',
    preparationTime: 15,
    servings: 2,
    difficulty: 'easy',
    category: 'principal',
    isVegan: true,
    isGlutenFree: false,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221fcf4c?w=400&h=400&fit=crop',
  },
  {
    title: 'Pumpkin Soup',
    description: 'Creamy and warm pumpkin soup with spices. Perfect for fall and autumn meals.',
    ingredients: 'Pumpkin puree, vegetable broth, onion, garlic, cream, nutmeg, cinnamon, salt, pepper',
    preparationTime: 30,
    servings: 4,
    difficulty: 'easy',
    category: 'principal',
    isVegan: false,
    isGlutenFree: true,
    rating: 4.2,
    imageUrl: 'https://images.unsplash.com/photo-1599340472-98eeeee68b6d?w=400&h=400&fit=crop',
  },
];

const seedDatabase = async () => {
  try {
    const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/recipes-db';

    await mongoose.connect(mongoURI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('✓ MongoDB connected');

    // Clear existing data
    await Recipe.deleteMany({});
    console.log('✓ Cleared existing recipes');

    // Insert recipes
    const inserted = await Recipe.insertMany(recipes);
    console.log(`✓ Inserted ${inserted.length} recipes`);

    console.log('\n📋 Sample Recipes:');
    recipes.slice(0, 5).forEach((r, i) => {
      console.log(`  ${i + 1}. ${r.title} (${r.category})`);
    });

    await mongoose.connection.close();
    console.log('\n✓ Database seeded successfully!\n');
  } catch (error) {
    console.error('✗ Error seeding database:', error.message);
    process.exit(1);
  }
};

seedDatabase();
